# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorName', models.CharField(max_length=50)),
                ('ipAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
