# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161220_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='accel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='accelRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='compassRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gyro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gyroRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orientRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('yaw', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='accel',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='accelRaw',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='compassRaw',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='gyro',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='gyroRaw',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='orient',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='orientRaw',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='compass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
